name: TerrainGenerator
version: '${project.version}'
main: me.abdulhamit.terraingenerator.TerrainGenerator
api-version: '1.20'
commands:
  generate:
    usage: /generate smoothness height
  resetseed:
    usage: /resetseed
